### ISSUE TITLE
Easiest way to convert `UnivariateFinite{MLJ.Multiclass{2}}` to a single number

### ISSUE THREAD

**Issue by rikhuijzer** [JuliaAI/CategoricalDistributions.jl#26]
Say that I have a `prediction::UnivariateFinite{MLJ.Multiclass{2}}` like
```
       UnivariateFinite{ScientificTypesBase.Multiclass{2}} 
       ┌                                        ┐ 
   0.0 ┤■■■■■■■■■■■■■■■■■■■■ 0.7999999999999999   
   1.0 ┤■■■■■ 0.2                                 
       └   
```
How do I convert this number to the prediction for class 1.0, that is, how do I get out 0.2 in this case? I found that the following works, but I guess that there is an easier way.
```julia
pair = MLJ.Distributions.params(prediction).probs
single = only(filter(p -> first(p) == 1.0, pair))
last(single)
```

**Comment by ablaom** [comment]
Those are weird class names, "0.1"  and "1.0". How did you get those?

Anyhow, you access probabilities just like you do for other `Distribution.Distributions`. If `d` is the distribution and `"c"` the class, you do `pdf(d, "c")`. Is this not clear from the readme?

**Comment by ablaom** [comment]
More examples are here: https://alan-turing-institute.github.io/MLJ.jl/dev/getting_started/#Fit-and-predict

**Comment by rikhuijzer** [comment]
> Sorry, I missed this one.
> 
> You access probabilities just like you do for other discrete `Distribution.Distributions`. If `prediction` is a single distribution and `"c"` the class, you do `pdf(prediction, "c")`. Is this not clear from the readme?

Ah, yes. Now I see. My bad.
