### ISSUE TITLE
Arithmetic on UnivariateFiniteArray

### ISSUE THREAD

**Issue by bkamins** [JuliaAI/CategoricalDistributions.jl#42]
The following seems inconsistent:
```
julia> u3 = UnivariateFinite(['x', 'z'], rand(3,2,2), pool=missing, ordered=true)
3×2 UnivariateFiniteArray{OrderedFactor{2}, Char, UInt8, Float64, 2}:
 UnivariateFinite{OrderedFactor{2}}(x=>0.552, z=>0.397)  UnivariateFinite{OrderedFactor{2}}(x=>0.634, z=>0.579)
 UnivariateFinite{OrderedFactor{2}}(x=>0.647, z=>0.742)  UnivariateFinite{OrderedFactor{2}}(x=>0.31, z=>0.531)
 UnivariateFinite{OrderedFactor{2}}(x=>0.431, z=>0.673)  UnivariateFinite{OrderedFactor{2}}(x=>0.755, z=>0.5)

julia> u3 * rand(2, 4)
ERROR: MethodError: no method matching zero(::UnivariateFinite{OrderedFactor{2}, Char, UInt8, Float64})
```

It seems that defining `zero` and `one` methods might be considered to be added for `UnivariateFinite`.

Also then:
```
*(x, d::UnivariateFinite) = d*x
```
definition should be reconsidered as it assumes that multiplication is commutative.

Or maybe support for multiplication with arrays was not intended?

(some other remarks regarding `/` would follow up depending on the intended design here)

**Comment by bkamins** [comment]
In https://github.com/JuliaAI/CategoricalDistributions.jl/pull/40 I also added test detecting method ambiguities and they additionally show that `*` and `/` design is problematic (and will lead to dispatch problems for users)

**Comment by ablaom** [comment]
I would say only multiplication and division by a scalar makes sense for `UnivariateFinite` objects. I never thought about multiplication of `UnivariateFiniteArray` with an array of scalars, but it makes sense to support that as well. I guess if we define `zero(::UnivariateFinite)` we'll get that automatically, right? 

I don't think it makes sense to define `one(::UnivariateFinite)`.

**Comment by OkonSamuel** [comment]
> Also then:
> 
> ```
> *(x, d::UnivariateFinite) = d*x
> ```
> 
> definition should be reconsidered as it assumes that multiplication is commutative.

Isn't that what we want. I cant find any reason why multiplication should be commutative.

**Comment by OkonSamuel** [comment]
> Or maybe support for multiplication with arrays was not intended?

Yes. I don't think it makes sense to support this as it would be difficult to provide satisfactory definitions of what `zero` and `one` should be for `UnivariateFinite` objects.

Element wise multiplication should suffice.

**Comment by bkamins** [comment]
>  I cant think of any reason why multiplication should be commutative.

Multiplication in general is not commutative, but you assume it in your code. Since you assume it then it would be good to restrict the allowed `x` to values that support commutative multiplication.

> Element wise multiplication should suffice.

OK. But then I would find it more natural to drop the:
```
*(d::UnivariateFinite, x) = _times(d, x, UnivariateFinite)
```
method and only keep the:
```
*(d::UnivariateFiniteArray, x::Number) = _times(d, x, UnivariateFiniteArray)
```
(same for division)

Do you have any real use-case when you want to allow `x` not to be a number and still support `*`?

Looking at your definitions in this context I understand that you want `UnivariateFinite` to define a vector space over some field. (and then indeed it makes sense to define `zero` for it, and not define `one` as it is not needed). And to restrict this field to be `Number` I think is reasonable enough.

The reason is, as I have noted above, that your current definitions might break code of some other people as:
```
julia> Test.detect_ambiguities(CategoricalDistributions,
                               recursive=true)
13-element Vector{Tuple{Method, Method}}:
 (*(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:49, *(c, p::SpecialFunctions.SimplePoly) in SpecialFunctions at ~\.julia\packages\SpecialFunctions\hefUc\src\expint.jl:9)
 (*(x, d::UnivariateFinite) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:52, *(p::SpecialFunctions.SimplePoly, c) in SpecialFunctions at ~\.julia\packages\SpecialFunctions\hefUc\src\expint.jl:8)
 (*(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:49, *(a, b::ChainRulesCore.AbstractThunk) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:126)
 (*(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:49, *(::Any, ::ChainRulesCore.NoTangent) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:65)
 (*(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:49, *(::Any, x::ChainRulesCore.NotImplemented) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:38)
 (*(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:49, *(::Any, ::ChainRulesCore.ZeroTangent) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:105)
 (*(x, d::UnivariateFinite) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:52, *(a::ChainRulesCore.AbstractThunk, b) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:125)
 (/(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:54, /(a, b::ChainRulesCore.AbstractThunk) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_types\thunks.jl:38)
 (*(x, d::UnivariateFinite) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:52, *(::ChainRulesCore.NoTangent, ::Any) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:64)
 (*(x, d::UnivariateFinite) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:52, *(x::ChainRulesCore.NotImplemented, ::Any) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:37)
 (*(x, d::UnivariateFinite) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:52, *(::ChainRulesCore.ZeroTangent, ::Any) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_arithmetic.jl:104)
 (/(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:54, /(::Any, x::ChainRulesCore.NotImplemented) in ChainRulesCore at ~\.julia\packages\ChainRulesCore\a4mIA\src\tangent_types\notimplemented.jl:43)
 (*(d::UnivariateFinite, x) in ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:49, *(x, d::UnivariateFinite) in CategoricalDistributions at ~\.julia\packages\CategoricalDistributions\eSHdo\src\arithmetic.jl:52)
```
so I think it is better to be more restrictive with typing than trying to be super general and introduce these ambiguities.

**Comment by ablaom** [comment]
Yes, I agree all those `x`'s in the code need `x::Number` annotations. The intention there was to only to define scalar (commutative) multiplication, and division by a scalar.  I haven't checked, but adding`zero(::UnivariateFinite)` will likely fix the error reported in the opening comment.

**Comment by bkamins** [comment]
> I haven't checked, but addingzero(::UnivariateFinite) will likely fix the error reported in the opening comment.

It would, but it is not strictly needed, as the error will not be present with scalar multiplication. Therefore I think that adding `zero` given your decision can be done later if someone needs it.

This is an example case:

```
julia> x = UnivariateFinite(['x', 'z'], rand(3, 2), pool=missing, ordered=true)
3-element UnivariateFiniteVector{OrderedFactor{2}, Char, UInt8, Float64}:
 UnivariateFinite{OrderedFactor{2}}(x=>0.695, z=>0.549)
 UnivariateFinite{OrderedFactor{2}}(x=>0.522, z=>0.277)
 UnivariateFinite{OrderedFactor{2}}(x=>0.00384, z=>0.98)

julia> sum(x)
         UnivariateFinite{OrderedFactor{2}}
     ┌                                        ┐
   x ┤■■■■■■■■■■■■■■■■■■■■■ 1.22083
   z ┤■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 1.80587
     └                                        ┘

julia> empty(x)
UnivariateFinite{OrderedFactor{2}, Char, UInt8, Float64}[]

julia> sum(empty(x))
ERROR: MethodError: no method matching zero(::Type{UnivariateFinite{OrderedFactor{2}, Char, UInt8, Float64}})
```

(the reason is - that in general - as I have noted above - if you define vector space it is natural to define `zero`)

**Comment by ablaom** [comment]
Okay, silly me. We only have a zero once we have labels. And labels are not type parameters.

**Comment by bkamins** [comment]
OK - this means that `zero` cannot be added and `sum(empty(x))` is expected to fail as there is no way to know the labels (as opposed to e.g. `NamedTuple` case).
