### ISSUE TITLE
Make UnicodePlots an optional dependency

### ISSUE THREAD

**Issue by andreasnoack** [JuliaAI/CategoricalDistributions.jl#49]
This package is an indirect dependency of ours and UnicodePlots adds more than eight seconds to the load time of our package so it would be helpful if UnicodePlots could be made an weak dependency as described in https://pkgdocs.julialang.org/dev/creating-packages/#Transition-from-normal-dependency-to-extension

**Comment by chriselrod** [comment]
Using `@time_imports`, I get
```julia
  20394.7 ms  UnicodePlots
      2.1 ms  UnicodePlots → UnitfulExt
     19.5 ms  CategoricalDistributions
```

**Comment by ablaom** [comment]
I'd support this change which makes sense. 

We keep the first `show` and the second goes into the UnicodePlots glue code:

https://github.com/JuliaAI/CategoricalDistributions.jl/blob/5c62c4e70b27c153e97773e5374a89a847595812/src/methods.jl#L82

This the only place UnicodePlots is used. 

I can't make this a priority just now, but can promise a timely review if someone wants to make a PR.

**Comment by t-bltg** [comment]
> That's 20 seconds loading UnicodePlots.

This is weird, it should be around 4 s. On what OS is that ?

https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/186 will also improve load times by reducing dependencies (merged, but not yet released).

**Comment by chriselrod** [comment]
Fedora, Linux.

**Comment by t-bltg** [comment]
Thanks, I'd be interested in reading suggestions on how to make the `UnicodePlots` experience smoother.

There is some latency involved by loading compiled code generated by precompile statements (tracked by https://github.com/JuliaPlots/UnicodePlots.jl/issues/324, with no immediate solution (except [disabling the precompilation workload](https://timholy.github.io/SnoopCompile.jl/dev/snoop_pc) with the effect of worsening TTFP)):
```julia
$ julia
julia> VERSION
v"1.9.0-beta4"
julia> using SnoopPrecompile, Preferences
julia> Preferences.set_preferences!(SnoopPrecompile, "skip_precompile" => ["UnicodePlots"]; force = true)
julia> exit(0)
$ julia -e 'using UnicodePlots'  # precompile
$ julia
julia> @time using UnicodePlots
  2.536887 seconds (3.35 M allocations: 230.944 MiB, 6.89% gc time, 8.91% compilation time: 17% of which was recompilation)

# previously, with precommpile workload: 
  4.223118 seconds (5.61 M allocations: 368.600 MiB, 6.43% gc time, 4.18% compilation time: 22% of which was recompilation)
```

Some improvements (2s, 32%) have been made in https://github.com/JuliaPlots/UnicodePlots.jl/pull/332 following https://github.com/JuliaPlots/UnicodePlots.jl/issues/331 using package extensions - weak deps.

IMO the load time in the range [2s, 4s] is reasonable now for a plotting package, but this is subjective (tradeoff for TTFP) and feedback would be appreciated.

**Comment by ablaom** [comment]
@t-bltg Thanks for the update. It's reassuring to know there is clearly a concerted effort to optimise. I don't have any suggestions on how to improve things there. 

I think the case for making UnicodePlots a weak dependency of CategoricalDistributions remains strong. It's only there for pretty printing and CategoricalDistributions will sit pretty low in the package food chain.

**Comment by ablaom** [comment]
Note to self: 

Current load time for UnicodePlots 3.4.0 is about 13 times that of Distributions 25.82 in a `@time_imports using CategoricalDistributions` benchmark.
